#配置server
server:
  port: 16969
  servlet:
    context-path: /m_blog_management
    session:
      tracking-modes: cookie
#配置spring
spring:
  #不同工程发布到同一tomcat下，必须要jmx区分开
  jmx:
    default-domain: m_blog_management
  #thymeleaf不进行页面缓存，方便页面热修改
  thymeleaf:
    cache: false
  #设置url后缀自定义设置
  mvc:
    pathmatch:
      use-suffix-pattern: false
      use-registered-suffix-pattern: true
    contentnegotiation:
      favor-path-extension: false
# 配置mybatis
mybatis:
  type-aliases-package: com.luzhoumin.mblog.management
  mapper-locations: classpath:com.luzhoumin.mblog.management.mapper.**.xml
#配置日志
debug: true
#配置数据库
druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    url: jdbc:mysql://localhost:3306/mblog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot1
    initial-size: 5
    min-idle: 1
    max-active: 100
    max-wait: 60000
    validation-query: SELECT 1
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
  slave:
    url: jdbc:mysql://localhost:3306/mblog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot1
    initial-size: 5
    min-idle: 1
    max-active: 100
    max-wait: 60000
    validation-query: SELECT 1
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
